export default [
  {
    id: "0",
    label: "Memory",
    target: "home",
    iconDefault: require("@/assets/icons/home.png"),
    iconFocus: require("@/assets/icons/home-cur.png"),
    bgcDefault: "rgba(255, 255, 255, 0.2)",
    bgcFocus: "#E6A23C",
    focus: true,
  },
  {
    id: "1",
    label: "我的文章",
    target: "myPassage",
    iconDefault: require("@/assets/icons/myPassage.png"),
    iconFocus: require("@/assets/icons/myPassage-cur.png"),
    bgcDefault: "rgba(255, 255, 255, 0.2)",
    bgcFocus: "#67C23A",
    focus: false,
  },
  {
    id: "2",
    label: "我的收藏",
    target: "myCollection",
    iconDefault: require("@/assets/icons/myCollection.png"),
    iconFocus: require("@/assets/icons/myCollection-cur.png"),
    bgcDefault: "rgba(255, 255, 255, 0.2)",
    bgcFocus: "#F56C6C",
    focus: false,
  },
  {
    id: "3",
    label: "系统维护",
    target: "myCollection",
    iconDefault: require("@/assets/icons/setting.png"),
    iconFocus: require("@/assets/icons/setting-cur.png"),
    bgcDefault: "rgba(255, 255, 255, 0.2)",
    bgcFocus: "#409EFF",
    focus: false,
  },
];
